travis:
  secure:
    BINSTAR_TOKEN: sc7Xo8wknA9zJZTQdpnYsrVqnFmg9NY4rELnIDnGV2p8oCWLDgdECQPCTS0WDRnL2BJFYf1fWV/dSgssZfhawRbj6a3Rp7J/3LaqkLT+A7P6BTSNnBaicH/Pt4dzPJIrCx0sZLvyXBOVbalv87nzW5+RmXtSKLT4L7aElNc4Ez0SwI+lGGRL0Npdjvk2fR9hpbjAOklFUm3iq7+/bdmmlLednlbiznarJac1mPZBkxR+bIQlZOyd6wdc1m9tTZehi+x7tHosqo/rFfNrX7YF0S5ahY2PCEr+tDyF2qD2PdVSnpJkjWTHlMbVKW1MUx3stYWOD6oKvEm7VZXaLxXDqjWKw9GmjxtcrFVFmXLyW1Vv6QeCBzYmKYOoiPWElAWbXTRWk6npOS7ctNDllyWDvjPSjpUBkZxdGyR8nxItfp0z6/bke2CIFFvosJbfPAcr7/KqcZdUimc1zVxfxBITbQbRKQc8k5c6ySim8GQ16MeAdSQT3VNeCQagH05AKB3uxedpWZngJk46reoJzkuoUSJ9bOY0jCefMg3wnxdDHp14cn4dsHdqCDZzm8btoUgTgMs4uqzlHr3LPtFBAif2DShU2Zkw8+7BRB9SgyO6XeKMutjD37SLQIOxyVHDvHyZ8i2H3ZdGgiRXj60jRGDdJFDOS7Ia492zj/3zmJX8Q6A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
