travis:
  secure:
    BINSTAR_TOKEN: tcjUWx+NtcIEyNPyvzlpsU7yfnHC3Vey58paLgZYfkDPyyMWyHRWx08+H8ZPwEdomdQnc2YjSJFWCm8W3W8xctvAUTdY4QLaLEt84/+xNPk1GsSOFBOgaBbRwu8n1khSbc3VR0O0n2CCfwaM3DaWDtsuAR3CsInhRgZHN7ncnP9twp///4ltxMV+DObShCmCthWBg8kiAej3V75v3Wo6RLaPWEgT+1t+QqvjVe31r6KZxsR/J/MPUUeE9JP85RB1ZzKarMI/fpreSvZzJQGUCYia1bVjGw7mlQe5q/2hCSGgpHJcKyse/K9k+AwJtedyAaeXN/YZxDC+LE1eTtrHaBupGEakG9h2LCiU8fcNNr3B9zonBQU1SLByvklbpvDdgvnJ+wItQzbzM5tAHyCqPg/6PtMQNo51Akzsi8mzWer8FoD5aLDX1XyrlZQ8LxSiWFAB99Zl5gBDgSxeXRVQVZu5qgM+YYwOESPqHPaZCsoXdJyvUOjlkVQOdja0Bvf3LpN2LwxZSmyuCeGlaW24vFvyOs3LIL8pzUTNvFD4w9y8BYFIWcBJLAax9h3zXxdA+Wu6lSS4wZEnUGbF46WJl/DEtl7ANl2MbWLwHBwik6G/aH5zqy6gE2kXN44KkVHGWqYypJF40+yUStfjUsj4x9r0FbRsnalVi93t3W1vXpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
